ALTER TABLE push_outbox
  MODIFY title VARCHAR(180) CHARACTER SET utf8mb4 NOT NULL,
  MODIFY body VARCHAR(500) CHARACTER SET utf8mb4 NOT NULL,
  MODIFY target_url VARCHAR(300) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'index.php';
